# Generated by Django 6.0.2 on 2026-05-23 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFieldConfidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("low", "低"), ("mid", "中")], max_length=10
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("primary", "主コンタクト"),
                            ("active", "副コンタクト"),
                            ("inactive", "非アクティブ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("duplicate_checked_at", models.DateTimeField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, default="ja", max_length=10)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salutation_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "qualification",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "catchphrase",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("branch", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                (
                    "personal_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "personal_fax",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("website", models.CharField(blank=True, default="", max_length=500)),
                ("twitter", models.CharField(blank=True, default="", max_length=255)),
                ("linkedin", models.CharField(blank=True, default="", max_length=500)),
                ("facebook", models.CharField(blank=True, default="", max_length=500)),
                ("github", models.CharField(blank=True, default="", max_length=255)),
                ("instagram", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.businesscard",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
