# Generated by Django 6.0.2 on 2026-05-06 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salutation_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "qualification",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "catchphrase",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("branch", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("mobile", models.CharField(blank=True, default="", max_length=50)),
                ("fax", models.CharField(blank=True, default="", max_length=50)),
                ("website", models.CharField(blank=True, default="", max_length=500)),
                ("twitter", models.CharField(blank=True, default="", max_length=255)),
                ("linkedin", models.CharField(blank=True, default="", max_length=500)),
                ("facebook", models.CharField(blank=True, default="", max_length=500)),
                ("github", models.CharField(blank=True, default="", max_length=255)),
                ("instagram", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.businesscard",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="persons.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactFieldConfidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中")], max_length=10
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidences",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact", "field_name"),
                        name="unique_contact_field_name",
                    )
                ],
            },
        ),
    ]
