# Generated by Django 6.0.2 on 2026-05-15 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="persons.person"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="previous_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactfieldconfidence",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactfieldconfidence",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confidences",
                to="contacts.contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "primary")),
                fields=("person",),
                name="unique_primary_contact_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactfieldconfidence",
            constraint=models.UniqueConstraint(
                fields=("contact", "field_name"), name="unique_contact_field_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactfieldconfidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__in", ["low", "medium"])),
                name="confidence_low_or_medium",
            ),
        ),
    ]
