# Generated by Django 6.0.2 on 2026-05-06 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("contacts", "0001_initial"),
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="duplicate_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="lang",
            field=models.CharField(default="ja", max_length=10),
        ),
        migrations.AddField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="contact",
            name="previous_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="previous_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("primary", "主コンタクト"),
                    ("active", "副コンタクト"),
                    ("inactive", "非アクティブ"),
                ],
                default="primary",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "primary")),
                fields=("person",),
                name="unique_primary_contact_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactfieldconfidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__in", ["low", "medium"])),
                name="confidence_low_or_medium",
            ),
        ),
    ]
