# Generated by Django 6.0.2 on 2026-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="alias_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="contact",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="handwritten_text",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="contact",
            name="language_composition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local_only", "現地語のみ"),
                    ("english_only", "英語のみ"),
                    ("mix_bilingual", "2 言語併記"),
                    ("other", "その他"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="legal_entity_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contact",
            name="legal_entity_type_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CP", "一般企業"),
                    ("LLP", "有限責任事業組合等"),
                    ("GOV", "政府機関・自治体"),
                    ("NPO", "NPO・NGO"),
                    ("REL", "宗教法人"),
                    ("EDU", "学校・教育機関"),
                    ("MED", "医療法人・病院"),
                    ("PRO", "士業法人"),
                    ("IND", "個人事業主"),
                    ("OTH", "その他"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="legal_entity_type_position",
            field=models.CharField(
                blank=True,
                choices=[("Pre", "前"), ("Post", "後"), ("Mid", "中間")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("last_first", "姓・名"),
                    ("first_last", "名・姓"),
                    ("single", "単一名"),
                    ("other", "その他"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="org_core_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="org_domain_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="org_fax",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contact",
            name="org_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contact",
            name="other_name_parts",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="other_printed_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contact",
            name="phonetic_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="rest_of_address",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="contact",
            name="salutation_name_is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
