# Generated by Django 6.0.2 on 2026-05-08 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("contacts", "0002_contact_created_by_contact_duplicate_checked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="business_card",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.businesscard",
            ),
        ),
    ]
