# Generated by Django 6.0.2 on 2026-05-23 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_alias_name_contact_city_contact_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="github",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="twitter",
        ),
        migrations.CreateModel(
            name="ContactSns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sns_type",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("github", "GitHub"),
                            ("blog", "Blog"),
                            ("youtube", "YouTube"),
                            ("line", "LINE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sns_id", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sns_accounts",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact", "sns_type", "sns_id"),
                        name="unique_contact_sns",
                    )
                ],
            },
        ),
    ]
