# Generated by Django 6.0.2 on 2026-05-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("contacts", "0003_alter_contact_business_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="business_card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.businesscard",
            ),
        ),
    ]
