# Generated by Django 6.0.2 on 2026-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_facebook_remove_contact_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='legal_entity_type_position',
            field=models.CharField(blank=True, choices=[('Pre', '前'), ('Post', '後'), ('Mid', '中間'), ('other', 'その他')], default='', max_length=10),
        ),
    ]
