# Generated by Django 6.0.2 on 2026-05-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_business_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lang",
            field=models.CharField(blank=True, default="ja", max_length=10),
        ),
    ]
