# Generated by Django 6.0.2 on 2026-06-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_legal_entity_type_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('edit_all_contacts', '他人の Contact を編集できる（横断権限、Phase 7 段2-B）')]},
        ),
    ]
