# Generated by Django 6.0.2 on 2026-06-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_delete_ja_salutation_low_cfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('primary', '主コンタクト'), ('active', '副コンタクト'), ('inactive', '旧コンタクト')], max_length=20),
        ),
    ]
