# Generated by Django 6.0.2 on 2026-06-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='display_name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name_is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
