# Generated by Django 6.0.2 on 2026-09-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_display_name_is_manual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('edit_all_contacts', '他人の Contact を編集できる（横断権限、Phase 7 段2-B）'), ('export_contact', 'コンタクトのCSVエクスポート権限'), ('import_contact', 'コンタクトCSV一括インポート権限')]},
        ),
    ]
