# Generated by Django 6.0.2 on 2026-09-08 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('mailings', '0011_alter_campaign_options'),
        ('persons', '0003_alter_person_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('phone', '電話'), ('visit', '訪問'), ('email', 'メール'), ('web_meeting', 'Web会議'), ('other', 'その他')], max_length=30)),
                ('direction', models.CharField(blank=True, choices=[('outgoing', '発信'), ('incoming', '受信')], default='', max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('place', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='mailings.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='deals.deal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活動記録',
                'verbose_name_plural': '活動記録',
                'ordering': ['-occurred_at'],
                'permissions': [('view_all_activities', 'Can view all activities'), ('edit_all_activities', 'Can edit all activities')],
            },
        ),
        migrations.CreateModel(
            name='ActivityPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('decision_maker', '決裁者'), ('contact_window', '窓口'), ('technical', '技術担当'), ('attendee', '同席者'), ('other', 'その他')], max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_persons', to='activities.activity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_persons', to='persons.person')),
            ],
            options={
                'verbose_name': '活動関係者（社外）',
                'verbose_name_plural': '活動関係者（社外）',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', '主担当'), ('support', '協力担当'), ('approver', '上長承認者'), ('observer', '閲覧者'), ('other', 'その他')], max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_users', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活動同席者（社内）',
                'verbose_name_plural': '活動同席者（社内）',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'occurred_at'], name='activities__user_id_2255ff_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['deal', 'occurred_at'], name='activities__deal_id_d0061b_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('campaign__isnull', True), ('deal__isnull', True)), models.Q(('campaign__isnull', True), ('deal__isnull', False)), models.Q(('campaign__isnull', False), ('deal__isnull', True)), _connector='OR'), name='activity_at_most_one_target'),
        ),
        migrations.AddConstraint(
            model_name='activityperson',
            constraint=models.UniqueConstraint(fields=('activity', 'person'), name='unique_activity_person'),
        ),
        migrations.AddConstraint(
            model_name='activityuser',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_user'),
        ),
    ]
