# Generated by Django 6.0.2 on 2026-09-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_cleanup_merged_activity_persons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL, verbose_name='実施者'),
        ),
        migrations.AlterField(
            model_name='activityperson',
            name='role',
            field=models.CharField(choices=[('decision_maker', '決裁者'), ('contact_window', '担当窓口'), ('technical', '技術・実務評価者'), ('attendee', '同席者'), ('other', 'その他')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activityuser',
            name='role',
            field=models.CharField(choices=[('primary', '主担当'), ('support', 'サポート'), ('approver', '上長承認者'), ('observer', '閲覧者'), ('other', 'その他')], max_length=30),
        ),
    ]
