# Generated by Django 6.0.2 on 2026-09-08 00:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('mailings', '0011_alter_campaign_options'),
        ('persons', '0003_alter_person_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('initial_meeting', '初回商談'), ('needs_analysis', 'ヒアリング・課題整理'), ('quotation', '見積提示'), ('under_review', '検討中'), ('internal_approval', '社内稟議中'), ('negotiation', '交渉'), ('won', '受注'), ('lost', '失注')], default='initial_meeting', max_length=30)),
                ('probability', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deal_type', models.CharField(blank=True, choices=[('new', '新規開拓'), ('expansion', '既存深耕'), ('renewal', '更新・継続')], default='', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('exhibition', '展示会・イベント'), ('referral', '紹介（既存客・取引先・知人）'), ('inbound_web', 'Webサイトからの問い合わせ'), ('inbound_direct', '電話・メールでの直接問い合わせ'), ('campaign', 'メールキャンペーン'), ('existing_customer', '既存客からの相談・追加依頼'), ('outbound', '自社からの営業（テレアポ・訪問・DM）'), ('other', 'その他')], default='', max_length=30)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_owned', to=settings.AUTH_USER_MODEL)),
                ('primary_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_primary', to='persons.person')),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_deals', to='mailings.campaign')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-updated_at'],
                'permissions': [('view_all_deals', 'Can view all deals'), ('edit_all_deals', 'Can edit all deals')],
            },
        ),
        migrations.CreateModel(
            name='DealPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('decision_maker', '決裁者'), ('contact_window', '窓口'), ('technical', '技術担当'), ('attendee', '同席者'), ('other', 'その他')], max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_persons', to='deals.deal')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_persons', to='persons.person')),
            ],
            options={
                'verbose_name': '案件関係者（社外）',
                'verbose_name_plural': '案件関係者（社外）',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', '主担当'), ('support', '協力担当'), ('approver', '上長承認者'), ('observer', '閲覧者'), ('other', 'その他')], max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_users', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '案件担当者（社内）',
                'verbose_name_plural': '案件担当者（社内）',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'stage', 'is_archived'], name='deals_deal_owner_i_daeab9_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'is_archived'], name='deals_deal_company_38c3b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealperson',
            constraint=models.UniqueConstraint(fields=('deal', 'person'), name='unique_deal_person'),
        ),
        migrations.AddConstraint(
            model_name='dealuser',
            constraint=models.UniqueConstraint(fields=('deal', 'user'), name='unique_deal_user'),
        ),
    ]
