# Generated by Django 6.0.2 on 2026-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealperson',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='主担当'),
        ),
        migrations.AddField(
            model_name='dealuser',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='編集権限'),
        ),
        migrations.AlterField(
            model_name='dealperson',
            name='role',
            field=models.CharField(choices=[('decision_maker', '決裁者'), ('influencer', '影響者'), ('contact_window', '窓口'), ('technical', '技術担当'), ('user', 'エンドユーザー'), ('attendee', '同席者'), ('other', 'その他')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dealuser',
            name='role',
            field=models.CharField(choices=[('owner', '主担当'), ('primary', '主担当'), ('sub', 'サブ担当'), ('support', '協力担当'), ('approver', '承認者'), ('observer', '閲覧者'), ('viewer', '参照者'), ('other', 'その他')], max_length=30),
        ),
    ]
