# Generated by Django 6.0.2 on 2026-09-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealperson',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='主担当'),
        ),
        migrations.AddField(
            model_name='dealuser',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='編集権限'),
        ),
        migrations.AlterField(
            model_name='dealperson',
            name='role',
            field=models.CharField(choices=[('decision_maker', '決裁者'), ('contact_window', '担当窓口'), ('technical', '技術・実務評価者'), ('attendee', '同席者'), ('other', 'その他')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dealuser',
            name='role',
            field=models.CharField(choices=[('primary', '主担当'), ('support', 'サポート'), ('approver', '上長承認者'), ('observer', '閲覧者'), ('other', 'その他')], max_length=30),
        ),
    ]
