# Generated by Django 6.0.2 on 2026-09-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealperson_is_primary_dealuser_can_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealperson',
            name='is_primary',
        ),
    ]
