# Generated by Django 6.0.2 on 2026-09-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_dealperson_is_primary'),
        ('persons', '0003_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='primary_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_primary', to='persons.person'),
        ),
    ]
