# Generated by Django 6.0.2 on 2026-09-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deallist_deal_deal_list'),
        ('permissions', '0002_default_access_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.deallist'),
        ),
    ]
