# Generated by Django 6.0.2 on 2026-09-19 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_all_access_lists', '全てのアクセスリストを閲覧できる')],
            },
        ),
        migrations.CreateModel(
            name='AccessListUserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('viewer', '閲覧者')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='permissions.accesslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list_user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['access_list', 'user'],
                'indexes': [models.Index(fields=['user', 'access_list'], name='permissions_user_id_073598_idx')],
                'constraints': [models.UniqueConstraint(fields=('access_list', 'user'), name='unique_access_list_user')],
            },
        ),
        migrations.CreateModel(
            name='ACLEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('permission_level', models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('viewer', '閲覧者'), ('none', '未設定')], max_length=20)),
                ('target_object_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='permissions.accesslist')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='permissions_target__9a9691_idx')],
            },
        ),
    ]
