# Generated by Django 6.0.2 on 2026-05-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="person",
            field=models.OneToOneField(
                blank=True,
                help_text="ログイン中のユーザに対応する Person（任意）。1 User : 0..1 Person、Person 側も 1 User までに制限。紐付け運用の詳細は §12 を参照。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accounts.department",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.department",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ldap_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="横断グループ（v1.5.0 では空運用も可）",
                related_name="members",
                to="accounts.ldapgroup",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="default_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="このRoleを付与した際に自動で入れるGroup",
                related_name="default_for_roles",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent"], name="accounts_de_parent__50b132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["auth_source"], name="accounts_de_auth_so_058ede_idx"
            ),
        ),
    ]
