# Generated by Django 6.0.2 on 2026-05-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("persons", "0002_alter_person_options_person_managed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="v1.5.0 では未使用。v1.6+ で運用方針確定",
                    ),
                ),
                (
                    "auth_source",
                    models.CharField(
                        choices=[("local", "ローカル"), ("ldap", "LDAP")],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "ldap_dn",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LdapGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("memo", models.TextField(blank=True)),
                (
                    "auth_source",
                    models.CharField(
                        choices=[("local", "ローカル"), ("ldap", "LDAP")],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "ldap_dn",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("link_user_to_person", "User と Person の紐付けを管理できる"),
                    ("retire_user", "ユーザを退職処理できる"),
                ]
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="auth_source",
            field=models.CharField(
                choices=[("local", "ローカル"), ("ldap", "LDAP")],
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ldap_dn",
            field=models.CharField(
                blank=True,
                help_text="LDAP 同期時の突合キー（LDAP 由来ユーザのみ）",
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="person",
            field=models.OneToOneField(
                blank=True,
                help_text="ログイン中のユーザに対応する Person（任意）。1 User : 0..1 Person、Person 側も 1 User までに制限。紐付け運用の詳細は §12 を参照。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="persons.person",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "auth_source",
                    models.CharField(
                        choices=[("local", "ローカル"), ("ldap", "LDAP")],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "ldap_dn",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounts.department",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.department",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ldap_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="横断グループ（v1.5.0 では空運用も可）",
                related_name="members",
                to="accounts.ldapgroup",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="画面表示名（例: 管理者, 営業, 閲覧者）",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="プログラム判定用の安定キー（admin, sales, viewer）。作成後の変更不可。変更したい場合はマイグレーション必須",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="このRoleを付与した際に自動で入れるGroup",
                        related_name="default_for_roles",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent"], name="accounts_de_parent__50b132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["auth_source"], name="accounts_de_auth_so_058ede_idx"
            ),
        ),
    ]
