# Generated by Django 6.0.2 on 2026-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="signature",
            field=models.TextField(
                blank=True,
                default="",
                help_text="メール送信時の署名（プレーンテキスト、HTML タグ不可）。v1.6 メール配信機能で末尾に挿入。仕様書 §4.14.1",
            ),
        ),
    ]
