# Generated by Django 6.0.2 on 2026-06-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fix_tag_editor_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('link_user_to_person', 'User と Person の紐付けを管理できる'), ('retire_user', 'ユーザを退職処理できる'), ('assign_role_to_user', 'ユーザにロールを割り当てられる')]},
        ),
    ]
