# Generated by Django 6.0.2 on 2026-05-26 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0002_person_is_unsubscribed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "タグカテゴリ",
                "verbose_name_plural": "タグカテゴリ",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="タグカテゴリ（必須）。カテゴリ削除でタグが連鎖削除されないよう PROTECT。カテゴリは論理削除運用（§4.9A）",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="tags.tagcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "タグ",
                "verbose_name_plural": "タグ",
                "ordering": ["category__sort_order", "name"],
                "permissions": [("assign_tag", "Person にタグを付与・解除できる")],
            },
        ),
        migrations.CreateModel(
            name="TagAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="persons.person",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "タグ付与",
                "verbose_name_plural": "タグ付与",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tag", "person"), name="unique_tag_person"
                    )
                ],
            },
        ),
    ]
