# Generated by Django 6.0.2 on 2026-05-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actionlogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionlog",
            old_name="extra",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="actionlog",
            name="diff",
        ),
    ]
