"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env を読み込む（OS 環境変数を優先するため override=False）
load_dotenv(BASE_DIR / ".env", override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-8+apke5-n!p08)eom4=c7s@x*(g-0g=3#bqnuodgt#z31#hph$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.3.135", "192.168.1.135"]

INTERNAL_IPS = ["127.0.0.1", "192.168.3.135", "192.168.1.135"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "home",
    "back_navigator",
    "ui_components",
    "cards",
    "persons",
    "contacts",
    "duplicates",
    "actionlogs",
    "tags",
    "mailings",
]

AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Card detector backend ("opencv" | "ai")
CARD_DETECTOR_BACKEND = os.getenv("CARD_DETECTOR_BACKEND", "opencv")

# OCR backend ("claude_sonnet_4_6" | "worker_cowork")
# claude_sonnet_4_6: Claude API（OcrService）。worker_cowork: media/ocr_json の JSON を読む。
OCR_BACKEND = os.getenv("OCR_BACKEND", "claude_sonnet_4_6")

# OCR pipeline: processing 状態が stuck と判断するまでの分数（stuck sweeper 用）
OCR_STUCK_THRESHOLD_MINUTES = 30


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "accounts:login"


# ============================================================
# 認証バックエンド + LDAP 連携（v1.5.0 / 仕様書 §5）
# ============================================================
# v1.5.1: AUTH_BACKEND=local 環境で python-ldap / django-auth-ldap がインストール
# されていなくても manage.py runserver が起動できるよう、LDAP 関連 import と
# グローバル評価を AUTH_BACKEND in ("ldap", "both") 条件下に集約した。
# OSS 配布時、LDAP を使わない利用者にまで python-ldap のインストールを強制しない。

AUTH_BACKEND = os.getenv("AUTH_BACKEND", "local")

if AUTH_BACKEND in ("ldap", "both"):
    # python-ldap / django-auth-ldap は AUTH_BACKEND が ldap/both のときのみ要求する。
    # local では未インストールでも起動できるよう、import 自体を条件分岐内に置く。
    import ldap
    from django_auth_ldap.config import LDAPSearch

    # ldap / both いずれも LDAP を試した後に local フォールバック（緊急時のローカル
    # 管理者用）するため AUTHENTICATION_BACKENDS は同一。
    AUTHENTICATION_BACKENDS = [
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

    # django-auth-ldap 標準設定（実認証時に使用）
    AUTH_LDAP_SERVER_URI = os.getenv("LDAP_SERVER_URI", "")
    AUTH_LDAP_BIND_DN = os.getenv("LDAP_BIND_DN", "")
    AUTH_LDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD", "")

    # username 突合属性（AD: sAMAccountName / LDAP: uid）。.env で切替可能。
    LDAP_USER_USERNAME_ATTR = os.getenv("LDAP_USER_USERNAME_ATTR", "sAMAccountName")

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.getenv("LDAP_USER_SEARCH_BASE", ""),
        ldap.SCOPE_SUBTREE,
        f"({LDAP_USER_USERNAME_ATTR}=%(user)s)",
    )

    # LDAP 属性 → CustomUser フィールド マッピング（仕様書 §5.3）
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": LDAP_USER_USERNAME_ATTR,
        "email": "mail",
        "first_name": "givenName",
        "last_name": "sn",
    }

    # キャッシュ設定（仕様書 §5.2）
    AUTH_LDAP_CACHE_TIMEOUT = (
        int(os.getenv("LDAP_CACHE_TTL", 3600))
        if os.getenv("LDAP_CACHE_ENABLED") == "true"
        else 0
    )

    # v1.5.0 では auth.Group / Permission の自動同期は使わない
    # （memberOf は accounts/ldap_sync.py で LdapGroup として独自管理、仕様書 §5.4）
    AUTH_LDAP_MIRROR_GROUPS = False
    AUTH_LDAP_FIND_GROUP_PERMS = False
else:
    # AUTH_BACKEND=local（および未知値の fallback）：LDAP モジュールは一切ロードしない。
    AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]


# --- メール送信設定 ---
# .env から os.getenv で読む（既存方式に統一）。.env 不在でも壊れない既定値を持たせる。
# 型変換：PORT は int、USE_TLS/USE_SSL は DEBUG 行と同じ bool 慣用。
# 注意：EMAIL_USE_TLS と EMAIL_USE_SSL を同時 True にしない（Django 起動時エラー）。
#       587 運用なら TLS=True / SSL=False。
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "")
