"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env を読み込む（OS 環境変数を優先するため override=False）
load_dotenv(BASE_DIR / ".env", override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-8+apke5-n!p08)eom4=c7s@x*(g-0g=3#bqnuodgt#z31#hph$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.3.135"]

INTERNAL_IPS = ["127.0.0.1", "192.168.3.135"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "back_navigator",
    "cards",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Card detector backend ("opencv" | "ai")
CARD_DETECTOR_BACKEND = os.getenv("CARD_DETECTOR_BACKEND", "opencv")

# OpenCV 切り出し（rev2 方式）— 未確定パラメータ（評価基準で詰める・仮値）
# 採否の主基準は縦横比（detector 側の確定値 1.6〜1.8）。以下はサイズ下限・統合の補助で、
# いずれも仮値・未確定。正本 docs/OpenCV/名刺画像前処理_設計方針_OpenCV_OSD_rev2.md
# §1.2.4（絶対下限）／§1.4・§3.2・§4.2（統合の IoU・採用座標）参照。値は後で調整する前提。
OPENCV_MIN_CARD_AREA_PX = 8000           # OCR 不能な極小候補を落とす緩い絶対下限[px^2]（仮値・未確定）
OPENCV_DEDUP_IOU_THRESHOLD = 0.30        # マスク横断 重複統合の IoU しきい値（仮値・未確定）
OPENCV_DEDUP_CENTER_DIST_RATIO = 0.50    # 中心距離 ≤ ratio×対角線 を IoU と併用（仮値・未確定）

# OCR pipeline: processing 状態が stuck と判断するまでの分数（stuck sweeper 用）
OCR_STUCK_THRESHOLD_MINUTES = 30

# Tesseract OSD（向き判定・rev2 第2部）。OCR 前に名刺クロップを正立化する。
# TESSERACT_CMD: tesseract 実行ファイルのパス。空なら pytesseract の既定（PATH 上の tesseract）を使う。
#   コードに固定パスを書かず、ここ（環境変数 TESSERACT_CMD）で与える。
TESSERACT_CMD = os.getenv("TESSERACT_CMD", "")
# image_to_osd のタイムアウト秒。
OSD_TIMEOUT_SEC = float(os.getenv("OSD_TIMEOUT_SEC", "10"))
# Tesseract OCR 記録用言語（image_to_string / image_to_data）。縦書き名刺があるため vertical も併用。
# 記録・分析専用であり、向き判定やクロップ採否のロジックには使わない。
TESSERACT_OCR_LANG = os.getenv("TESSERACT_OCR_LANG", "jpn+jpn_vert")


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
