server {
    listen 80;
    server_name 192.168.100.136 g.network-tokai.jp;
    
    # HTTPアクセスをHTTPSへリダイレクト
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 192.168.100.136 g.network-tokai.jp;

    ssl_certificate     /etc/nginx/certs/freegroup2.crt;
    ssl_certificate_key /etc/nginx/certs/freegroup2.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 20M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        resolver 127.0.0.11 valid=10s;
        set $upstream_web http://web:8000;
        proxy_pass $upstream_web;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
