# Generated by Django 6.0.2 on 2026-09-08 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', '有効'), ('merged', '統合済み'), ('archived', 'アーカイブ')], default='active', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_companies', to='companies.company')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'ordering': ['organization'],
                'permissions': [('merge_company', 'Can merge companies')],
            },
        ),
        migrations.CreateModel(
            name='CompanyDuplicateCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('rank', models.CharField(choices=[('exact_match', '完全一致'), ('possible_high', '可能性高'), ('possible_mid', '可能性中'), ('possible_low', '可能性低')], max_length=20)),
                ('review_status', models.CharField(choices=[('pending', '未処理'), ('merged', '統合済み'), ('different_company', '別会社と判断'), ('invalidated', '無効化')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_as_a', to='companies.company')),
                ('company_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_as_b', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会社重複候補',
                'verbose_name_plural': '会社重複候補',
                'ordering': ['-score', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('review_status', 'pending')), fields=('company_a', 'company_b'), name='unique_pending_company_pair')],
            },
        ),
    ]
