# Generated by Django 6.0.2 on 2026-09-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0001_initial'),
        ('persons', '0004_personlist_person_person_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmergelog',
            name='person_list_before_merge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persons.personlist'),
        ),
    ]
