# Generated by Django 6.0.2 on 2026-05-06 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_created_by_contact_duplicate_checked_at_and_more"),
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from_set",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "通常"),
                    ("merged", "統合済み"),
                    ("archived", "アーカイブ"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
