# Generated by Django 6.0.2 on 2026-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_unsubscribed",
            field=models.BooleanField(
                default=False,
                help_text="メール配信停止フラグ（Unsubscribe レコードの派生情報、高速フィルタ用キャッシュ）。通常は Phase 3 で実装する unsubscribe_person() / cancel_unsubscribe() 経由で更新する。仕様書 §4.14.2 / §4.14.2.1",
            ),
        ),
    ]
