# Generated by Django 6.0.2 on 2026-05-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": [
                    ("undo_merge", "マージ復元を実行できる"),
                    ("merge_person", "Person マージを実行できる"),
                    ("link_user", "User-Person 紐付けを設定できる"),
                ]
            },
        ),
        migrations.AddField(
            model_name="person",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
