# Generated by Django 6.0.2 on 2026-06-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_is_unsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', '通常'), ('merged', 'マージ済み'), ('archived', 'アーカイブ')], default='active', max_length=20),
        ),
    ]
