# Generated by Django 6.0.2 on 2026-09-19 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('persons', '0003_alter_person_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('edit_scope', models.CharField(choices=[('creator_only', '作成者のみ'), ('all_editors', 'リスト編集者全員')], default='all_editors', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_lists', to='permissions.accesslist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('edit_all_persons', '全てのパーソンを編集できる')],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='person_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='persons.personlist'),
        ),
    ]
