# Generated by Django 6.0.2 on 2026-09-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_personlist_person_person_list'),
        ('permissions', '0002_default_access_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='persons.personlist'),
        ),
    ]
