# Generated by Django 6.0.2 on 2026-09-19 09:17

import django.db.models.deletion
import persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_person_person_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('undo_merge', 'マージ復元を実行できる'), ('merge_person', 'Person マージを実行できる'), ('link_user', 'User-Person 紐付けを設定できる'), ('view_all_persons', '全てのパーソンを閲覧できる'), ('edit_all_persons', '全てのパーソンを編集できる')]},
        ),
        migrations.AlterField(
            model_name='person',
            name='person_list',
            field=models.ForeignKey(default=persons.models.get_or_create_default_person_list, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='persons.personlist'),
        ),
    ]
