# Generated by Django 6.0.2 on 2026-05-26 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0002_person_is_unsubscribed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "subject",
                    models.CharField(
                        help_text="件名（プレーンテキスト、差し込み変数可、HTML 不可、§4.3）",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="本文（プレーンテキスト）。差し込み変数 {{...}} と {% tracked_link %} / {% unsubscribe_link %} の 3 種記法のみ可。HTML タグは書かない（rev9 確定、§1.1）。Phase 1 で body_html → body に改名"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="代替テキスト。body_text_is_manual=True なら手動値として使用、False（既定）なら配信時に html2text 等で自動生成（§4.3）",
                    ),
                ),
                ("body_text_is_manual", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "メールテンプレート",
                "verbose_name_plural": "メールテンプレート",
                "ordering": ["-updated_at"],
                "permissions": [
                    ("manage_template", "メールテンプレートを作成・編集・削除できる")
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingConfig",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_address", models.TextField()),
                (
                    "unsubscribe_contact",
                    models.CharField(
                        help_text="配信停止連絡先（メアド / 電話 / URL）。特電法フッターで使用",
                        max_length=200,
                    ),
                ),
                (
                    "dkim_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DKIM 署名対象ドメイン。Phase 8 で本格運用（§4.13）",
                        max_length=200,
                    ),
                ),
                (
                    "dkim_selector",
                    models.CharField(blank=True, default="default", max_length=50),
                ),
                (
                    "dkim_private_key",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="DKIM 秘密鍵（Phase 8 で管理コマンドが生成）",
                    ),
                ),
                (
                    "default_newsletter_sender_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="メルマガ方式のデフォルト差出人アドレス。値を入れる場合は dkim_domain 配下のドメインに限定（§4.13 rev6 補足）",
                        max_length=254,
                    ),
                ),
                (
                    "default_newsletter_sender_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "メール配信設定",
                "verbose_name_plural": "メール配信設定",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="mailing_config_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "extraction_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="抽出条件スナップショット（再抽出補助のみ、配信時は参照しない）。JSON 具体スキーマは §19 残論点、Phase 1 ではフィールド定義のみ（§11.4.3.1）",
                        null=True,
                    ),
                ),
                (
                    "members_frozen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="メンバー凍結時刻。リスト作成・再抽出時に更新する（§4.11）",
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "リスト",
                "verbose_name_plural": "リスト",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingListMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="凍結された時点（§4.12）"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="mailings.mailinglist",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_list_memberships",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "リストメンバー",
                "verbose_name_plural": "リストメンバー",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mailing_list", "person"),
                        name="unique_mailing_list_person",
                    )
                ],
            },
        ),
    ]
