# Generated by Django 6.0.2 on 2026-05-28 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contact_legal_entity_type_position"),
        ("mailings", "0001_initial"),
        ("persons", "0002_person_is_unsubscribed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftBounceCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="カウント対象メアド。昇格時・送信成功時に物理削除されるため 素の unique=True で十分（SuppressedEmail の partial unique と対照、§4.8A）",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0, help_text="現時点の連続ソフトバウンス回数"
                    ),
                ),
                (
                    "last_bounce_at",
                    models.DateTimeField(
                        help_text="最後にソフトバウンスを観測した日時"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ソフトバウンスカウンタ",
                "verbose_name_plural": "ソフトバウンスカウンタ",
                "ordering": ["-last_bounce_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="キャンペーン名（管理用、受信者には見えない）",
                        max_length=200,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="予約配信日時。rev9 で即時配信モード廃止。status=scheduled 遷移時の未来日時必須は Phase 3 のサービス層・フォーム層で担保（§4.2）",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("scheduled", "予約配信待機中"),
                            ("sending", "配信中"),
                            ("done", "配信完了"),
                            ("failed", "配信失敗"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sender_mode",
                    models.CharField(
                        choices=[
                            ("creator", "送信元（メール作成者）"),
                            ("newsletter", "送信元（メルマガ）"),
                        ],
                        default="creator",
                        help_text="送信元方式（§7.8、別表 C.26）",
                        max_length=20,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="メルマガ方式時の差出人アドレス（自社 DKIM 許可ドメイン配下のみ）。メール作成者方式時は空（created_by から取得、§7.8.3）",
                        max_length=254,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="メルマガ方式時の差出人名。メール作成者方式時は空",
                        max_length=200,
                    ),
                ),
                (
                    "apply_unsubscribe_filter",
                    models.BooleanField(
                        default=True,
                        help_text="Unsubscribe フィルタ適用フラグ。default=True（安全側）。sender_mode='newsletter' のときは構造的に常時 True 固定（特電法事故防止）。強制ロジックは Phase 3 のサービス層・フォーム層（§7.8.4）",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mailing_list",
                    models.ForeignKey(
                        help_text="宛先リスト（必須、rev12 で必須 FK 化）。リスト削除でキャンペーン履歴が壊れないよう PROTECT。リストは論理削除運用（§4.11 / §11）",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="mailings.mailinglist",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="mailings.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "キャンペーン",
                "verbose_name_plural": "キャンペーン",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_all_campaigns",
                        "他人の配信キャンペーン・配信レポートを閲覧できる",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackingLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.URLField(max_length=2000)),
                (
                    "token",
                    models.CharField(
                        help_text="URL 埋め込みトークン（生成は Phase 3 build()、自動生成を Phase 2 で仕込まない）",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "click_count",
                    models.IntegerField(
                        default=0, help_text="有効クリック回数（ボット除外後）"
                    ),
                ),
                (
                    "total_access_count",
                    models.IntegerField(
                        default=0, help_text="総アクセス回数（ボット含む）"
                    ),
                ),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_links",
                        to="mailings.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "トラッキングリンク",
                "verbose_name_plural": "トラッキングリンク",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_masked",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="マスク済み IP（IPv4 末尾 0、IPv6 下位ビットマスク）。保持日数経過後に NULL 上書き（Phase 3 の管理コマンド、§4.6）",
                        null=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("http_method", models.CharField(max_length=10)),
                ("is_valid_click", models.BooleanField()),
                (
                    "bot_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_get", "GET 以外"),
                            ("known_bot", "既知のボット"),
                            ("too_fast", "プリフェッチ"),
                            ("duplicate", "重複クリック"),
                            ("test_send", "テスト配信"),
                        ],
                        default="",
                        help_text="無効と判定された理由（is_valid_click=False 時のみ値あり、別表 C.23）",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracking_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="mailings.trackinglink",
                    ),
                ),
            ],
            options={
                "verbose_name": "クリックログ",
                "verbose_name_plural": "クリックログ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Unsubscribe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_email",
                    models.EmailField(
                        help_text="操作元のメアド文字列（Contact が消えても残す、§4.7）",
                        max_length=254,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unsubscribe_link", "配信停止リンク"),
                            ("manual", "管理者手動"),
                            ("api", "API 経由"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="配信停止解除日時（解除は論理削除、§4.7 設計趣旨）",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unsubscribes",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "配信停止履歴",
                "verbose_name_plural": "配信停止履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnsubscribeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="URL 埋め込みトークン（TrackingLink とは別 namespace、生成は Phase 3）",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="受信者の初回 GET 日時（§4.5A.2）",
                        null=True,
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="配信停止確定日時（POST、§4.5A.2）",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_links",
                        to="mailings.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "配信停止リンク",
                "verbose_name_plural": "配信停止リンク",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        help_text="配信先メアド（送信時点の値を凍結保存、§4.4.1）",
                        max_length=254,
                    ),
                ),
                (
                    "organization_at_send",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="送信時点の組織名（会社名）スナップショット。rev13 で本編 v1.6.0 の Contact.organization リネーム反映により company_at_send から改名",
                        max_length=255,
                    ),
                ),
                (
                    "full_name_at_send",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salutation_name_at_send",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "送信前"),
                            ("sent", "送信成功"),
                            ("failed", "送信失敗"),
                            ("bounced", "バウンス"),
                            ("unsubscribed", "配信停止"),
                        ],
                        default="pending",
                        help_text="5 値（pending/sent/failed/bounced/unsubscribed、別表 C.22）",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_histories",
                        to="mailings.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="配信時のプライマリーコンタクト（参考情報、マージ・削除で失われる可能性あり）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contacts.contact",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "配信履歴",
                "verbose_name_plural": "配信履歴",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "person"),
                        name="unique_delivery_history_campaign_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuppressedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="配信拒否メアド。unique=True は付けない（partial unique で制御、§4.8.1）。解除 → 再追加を IntegrityError なしで可能にするため",
                        max_length=254,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unsubscribe_generic", "代表メール配信停止"),
                            ("bounce_hard", "ハードバウンス"),
                            ("bounce_soft_promoted", "ソフトバウンス昇格"),
                            ("manual", "管理者手動"),
                            ("api", "API 経由"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "bounce_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="バウンスの場合の MTA 応答メッセージ等",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="配信拒否解除日時（論理削除、§4.8.1）",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "配信拒否メアド",
                "verbose_name_plural": "配信拒否メアド",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cancelled_at__isnull", True)),
                        fields=("email",),
                        name="unique_active_suppressed_email",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trackinglink",
            constraint=models.UniqueConstraint(
                fields=("campaign", "person", "original_url"),
                name="unique_tracking_link_campaign_person_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="unsubscribelink",
            constraint=models.UniqueConstraint(
                fields=("campaign", "person"),
                name="unique_unsubscribe_link_campaign_person",
            ),
        ),
    ]
