# Generated by Django 6.0.2 on 2026-05-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_softbouncecounter_campaign_trackinglink_clicklog_and_more"),
        ("persons", "0002_person_is_unsubscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryhistory",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_histories",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="trackinglink",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracking_links",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="unsubscribelink",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unsubscribe_links",
                to="persons.person",
            ),
        ),
    ]
