# Generated by Django 6.0.2 on 2026-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_deliveryhistory_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryhistory",
            name="failed_count",
            field=models.IntegerField(
                default=0,
                help_text="送信試行の累積失敗回数（§7.2.2）。CAMPAIGN_RECIPIENT_MAX_FAILURES に達したら「最終 failed」確定、status は failed のまま（別表 C.22 の 5 値は変更しない、§4.4）",
            ),
        ),
        migrations.AddField(
            model_name="deliveryhistory",
            name="last_failed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="最後の失敗日時（運用視認性・デバッグ用、§7.2.2 では任意）",
                null=True,
            ),
        ),
    ]
