# Generated by Django 6.0.2 on 2026-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_deliveryhistory_failed_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suppressedemail",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "manage_suppressed_email",
                        "配信拒否リストを編集できる（解除・手動追加、§14.1.1）",
                    )
                ],
                "verbose_name": "配信拒否メアド",
                "verbose_name_plural": "配信拒否メアド",
            },
        ),
    ]
