# Generated by Django 6.0.2 on 2026-05-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_unsubscribelink_target_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="template",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign",
                to="mailings.emailtemplate",
            ),
        ),
    ]
