# Generated by Django 6.0.2 on 2026-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_alter_campaign_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="論理削除フラグ（§12.4）。Campaign 論理削除サービスが Campaign と紐付くEmailTemplate を同一 atomic で True に更新する（OneToOne PROTECT のため物理削除不可）。一覧・詳細は is_archived=False のみ表示",
            ),
        ),
    ]
