# Generated by Django 6.0.2 on 2026-05-30 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_campaign_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="mailing_list",
            field=models.ForeignKey(
                blank=True,
                help_text="このキャンペーンの宛先リスト。配信を予約する時点までに必ず選んでください。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mailings.mailinglist",
            ),
        ),
    ]
