# Generated by Django 6.0.2 on 2026-05-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_alter_campaign_mailing_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="apply_unsubscribe_filter",
            field=models.BooleanField(
                default=True,
                help_text="配信停止を希望した宛先には送らない設定です。通常はオンのままにしてください。メルマガとして配信する場合は常時オンに固定されます。",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="配信を実行する日時。下書きの間は空のままで OK ですが、予約する時点で未来の日時を指定してください。",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="sender_email",
            field=models.EmailField(
                blank=True,
                help_text="メルマガとして配信する場合の差出人アドレス。自社の DKIM 設定済みドメインの配下を指定してください。",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="sender_mode",
            field=models.CharField(
                choices=[
                    ("creator", "送信元（メール作成者）"),
                    ("newsletter", "送信元（メルマガ）"),
                ],
                default="creator",
                help_text="送信元の名義を選びます。",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="sender_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="メルマガとして配信する場合の差出人名（受信メールの From 欄に表示されます）。",
                max_length=200,
            ),
        ),
    ]
