# Generated by Django 6.0.2 on 2026-06-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0010_alter_campaign_apply_unsubscribe_filter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'permissions': [('send_campaign', 'メール配信を実行できる（不可逆操作のため CRUD から分離、§14.1.2）'), ('view_all_campaigns', '他人の配信キャンペーン・配信レポートを閲覧できる'), ('export_report', '配信レポート CSV をダウンロードできる（§14.1.2）')], 'verbose_name': 'キャンペーン', 'verbose_name_plural': 'キャンペーン'},
        ),
    ]
