# Generated by Django 6.0.2 on 2026-05-06 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_file", models.ImageField(upload_to="originals/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "処理待ち"),
                            ("processing", "処理中"),
                            ("extracted", "完了"),
                            ("garbage", "無効画像"),
                            ("failed", "処理失敗"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("detected_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cards/%Y/%m/%d/"
                    ),
                ),
                ("card_index", models.IntegerField()),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("normal", "正位"),
                            ("rotate_90_cw", "時計回り90°"),
                            ("rotate_90_ccw", "反時計回り90°"),
                            ("rotate_180", "180°回転"),
                            ("mirror", "鏡像"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.originalimage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("original_image", "card_index"),
                        name="unique_original_image_card_index",
                    )
                ],
            },
        ),
    ]
