# Generated by Django 6.0.2 on 2026-04-28 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_file", models.ImageField(upload_to="originals/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未処理"),
                            ("extracted", "正常"),
                            ("garbage", "ゴミ画像"),
                            ("failed", "処理失敗"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("detected_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_image", models.ImageField(upload_to="cards/%Y/%m/%d/")),
                ("raw_json", models.JSONField()),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "未実行"),
                            ("processing", "実行中"),
                            ("success", "OCR成功"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.originalimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salutation_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("additional_names", models.JSONField(default=list)),
                ("alt_names", models.JSONField(default=list)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("emails", models.JSONField(default=list)),
                ("phones", models.JSONField(default=list)),
                ("mobiles", models.JSONField(default=list)),
                ("fax", models.JSONField(default=list)),
                ("websites", models.JSONField(default=list)),
                ("social_media", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.businesscard",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.person"
                    ),
                ),
            ],
        ),
    ]
