# Generated by Django 6.0.2 on 2026-05-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesscard",
            options={
                "permissions": [
                    ("create_card", "名刺カードを作成できる"),
                    ("edit_card", "名刺カードを編集できる"),
                    ("merge_card", "名刺カードをマージできる"),
                ]
            },
        ),
    ]
