# Generated by Django 6.0.2 on 2026-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="catchphrase",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="contact",
            name="qualification",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
