# Generated by Django 6.0.2 on 2026-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_contact_branch_contact_catchphrase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscard",
            name="orientation",
            field=models.CharField(default="normal", max_length=20),
        ),
    ]
