# Generated by Django 6.0.2 on 2026-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_businesscard_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalimage",
            name="exif_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
