# Generated by Django 6.0.2 on 2026-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_originalimage_exif_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='osd_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debugmask',
            name='mask_type',
            field=models.CharField(choices=[('diff', '輝度差 (diff)'), ('edge', 'エッジ (edge)'), ('sat', '彩度 (sat)'), ('or', 'OR 合成 (or)'), ('closed', 'クロージング (closed)'), ('adaptive', '局所二値化 生 (adaptive)'), ('diff_closed', '輝度差 クローズ (diff_closed)'), ('edge_closed', 'エッジ クローズ (edge_closed)'), ('sat_closed', '彩度 クローズ (sat_closed)'), ('adaptive_closed', '局所二値化 クローズ (adaptive_closed)')], max_length=16),
        ),
    ]
