# Generated by Django 6.0.2 on 2026-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_businesscard_orientation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscard",
            name="orientation",
            field=models.CharField(
                choices=[
                    ("normal", "正位"),
                    ("rotate_90_cw", "時計回り90°"),
                    ("rotate_90_ccw", "反時計回り90°"),
                    ("rotate_180", "180°回転"),
                    ("mirror", "鏡像"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
