# Generated by Django 6.0.2 on 2026-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_businesscard_osd_json_alter_debugmask_mask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='orientation_correction',
            field=models.CharField(blank=True, choices=[('rotated', '回転補正を実行'), ('kept', '据え置き（スコア<閾値）'), ('straight', '正立（補正不要）'), ('failed', '判定失敗で据え置き'), ('unexecuted', '未実行（本機能リリース前の過去データ）')], default='unexecuted', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='orientation_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
