# Generated by Django 6.0.2 on 2026-05-07 15:53

import cards.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_businesscard_ocr_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugMask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("diff", "輝度差 (diff)"),
                            ("edge", "エッジ (edge)"),
                            ("sat", "彩度 (sat)"),
                            ("or", "OR 合成 (or)"),
                            ("closed", "クロージング (closed)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mask_image",
                    models.ImageField(upload_to=cards.models._debug_mask_upload_path),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debug_masks",
                        to="cards.originalimage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("original_image", "mask_type"),
                        name="unique_original_image_mask_type",
                    )
                ],
            },
        ),
    ]
