# Generated by Django 6.0.2 on 2026-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_debugmask"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="debugmask",
            name="unique_original_image_mask_type",
        ),
        migrations.AddField(
            model_name="debugmask",
            name="attempt_no",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="debugmask",
            constraint=models.UniqueConstraint(
                fields=("original_image", "mask_type", "attempt_no"),
                name="unique_original_image_mask_type_attempt",
            ),
        ),
    ]
