# Generated by Django 6.0.2 on 2026-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_businesscard_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalimage",
            name="claimed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="originalimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "処理待ち"),
                    ("processing", "処理中"),
                    ("extracted", "完了"),
                    ("garbage", "無効画像"),
                    ("failed", "処理失敗"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
