# Generated by Django 6.0.2 on 2026-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_remove_debugmask_unique_original_image_mask_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscard",
            name="claimed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "OCR待ち"),
                    ("processing", "OCR処理中"),
                    ("done", "OCR完了"),
                    ("failed", "OCR失敗"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="raw_json_1",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="raw_json_2",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="businesscard",
            name="ocr_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("business_card", "名刺"),
                    ("not_business_card", "名刺ではない"),
                    ("insufficient_info", "情報不足"),
                    ("ocr_failed", "OCR失敗"),
                    ("others", "その他"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="originalimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "処理待ち"),
                    ("opencv_processing", "OpenCV処理中"),
                    ("cards_extracted", "OpenCV完了・OCR待ち"),
                    ("processing", "処理中"),
                    ("extracted", "完了"),
                    ("garbage", "無効画像"),
                    ("failed", "処理失敗"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
