# Generated by Django 6.0.2 on 2026-05-07 00:23
#
# ステップ1C-1: OriginalImage に debug_json フィールドを追加。
# OpenCV 名刺検出の中間データ（候補一覧・除外理由・透視変換失敗情報など）を
# キャッシュするための JSONField。None の場合は OriginalDetailView の GET 時に
# detect_cards_with_debug() が呼ばれ、結果が debug_json に保存される。
# masks 画像本体は同梱せず MEDIA_ROOT/debug_cache/<id>/mask_*.png に分離保存する。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_originalimage_claimed_at_alter_originalimage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalimage",
            name="debug_json",
            field=models.JSONField(
                blank=True,
                help_text="OpenCV 検出のデバッグ情報（中間データ）。None なら次回 GET 時に再計算される",
                null=True,
            ),
        ),
    ]
