# Generated by Django 6.0.2 on 2026-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_originalimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugmask',
            name='mask_type',
            field=models.CharField(choices=[('diff', '輝度差 生 (diff)'), ('edge', 'エッジ 生 (edge)'), ('sat', '彩度 生 (sat)'), ('adaptive', '局所二値化 生 (adaptive)'), ('diff_closed', '輝度差 クローズ (diff_closed)'), ('edge_closed', 'エッジ クローズ (edge_closed)'), ('sat_closed', '彩度 クローズ (sat_closed)'), ('adaptive_closed', '局所二値化 クローズ (adaptive_closed)')], max_length=16),
        ),
    ]
